-- Skills for Death Game & Cosmic Streamer Novel
-- Executes 12 skills for the novel creation method

SET @method_id = (SELECT id FROM novel_creation_method WHERE name = 'Death Game & Cosmic Streamer Novel' LIMIT 1);

INSERT INTO skill (name, description, description_en, instructions, instructions_en, novel_creation_method_id, is_active, sort_order, created_at)
VALUES 
-- 1. Story Hook
('death-story-hook-setting-gen', '生成「Story Hook」：设计突入其来的末日直播与主角在绝境下吸引天神打赏的开局', 'Generate Story Hook for Death Game',
'## 「Story Hook」生成 — 死亡直播赛

核心卖点是**无差别的残酷杀戮**与**高维生物（榜一大哥）的娱乐态度**之间产生的黑色幽默。

### 生成指南
1. **The Abduction Event (末日挟持)**：普通的一天，地铁/学校突然被结界封锁。半空中出现了一个长着翅膀、或者极其赛博朋克风的“鬼怪星探”。它笑着宣布：“恭喜各位地球人！你们成功被选为宇宙直播平台【星空网】的最新真人秀演员！本期生存名额：10%！”
2. **The First Broadcast (首播死局)**：手无寸铁的地球人面对立刻冲出来的怪物（或者被要求互相残杀）。无数蓝色弹幕在主角视网膜上刷过。
3. **The Protagonist’s Edge (狠人破局)**：在所有人都哭喊着找妈妈时，主角直接拿起灭火器砸烂了第一个怪物的头。这个极度疯狂的反差，瞬间让几万名高高在上的“星神（Constellations）”兴奋了起来，首充到账。',
'## "Story Hook" Generation — Death Game / Cosmic Streamer

The core selling point is the black comedy generated by the **indiscriminate brutal slaughter of humans** contrasting with the **bored, entertaining attitude of higher-dimensional beings (the VIP viewers).**

### Guide
1. **The Abduction Event**: A mundane day on the subway. Suddenly, a barrier seals the train. A cybernetic or floating fairy-like "Scout/Goblin" appears, cheerfully announcing: *"Congratulations Earthlings! You''ve been selected for the newest reality show on the Cosmic Broadcast Net! Survival quota for this tutorial: 10%!"*
2. **The First Broadcast**: Unarmed humans face a sudden monster attack (or are told to kill each other). Holographic blue chat messages begin scrolling rapidly across the MC''s retina.
3. **The Protagonist’s Edge**: While everyone screams for their mothers, the MC calmly picks up a fire extinguisher and caves in the first monster''s skull. This psychopathic contrast instantly excites the bored "Constellations" (Gods). The first donations roll in.', @method_id, 1, 1, NOW()),

-- 2. Core Premise
('death-core-premise-setting-gen', '生成「Core Premise」：设定主角的直播人设、坑天神的终极目标与赞助商关系', 'Generate Core Premise for Death Game',
'## 「Core Premise」生成 — 死亡直播赛

主角并不是真正的疯子（好吧有时候是），但为了**流量（硬通货）**，必须立人设。

### 生成指南
1. **The Persona (直播人设)**：是“绝不废话的冷酷杀手”、“极其腹黑算计的骗子（连天神都骗）”、还是“表面笑嘻嘻内心极其癫狂的小丑”？
2. **The Ultimate Goal (终极目标)**：从最开始的【赚够硬币买一瓶水活下去】，到【我要打上神界，把所有的榜一大哥全部宰了】。
3. **The Audience Dynamic (神与人的关系)**：高维生物把人类当蛐蛐。主角则把高维生物当成没见过世面、容易被带节奏的“ATM提款机”。',
'## "Core Premise" Generation — Death Game / Cosmic Streamer

The MC isn''t always an actual psycho, but to earn **Traffic/Coins (the hard currency for survival)**, they MUST establish a streaming persona.

### Guide
1. **The Persona**: Are they the "Ruthless, Silent Reaper," the "Manipulative Scammer (who even scams the Gods)," or the "Smiling Joker who is actually insanely unhinged"?
2. **The Ultimate Goal**: Scales up. Starts as [Earn enough coins to buy a 50ml bottle of water so I don''t die of thirst], and evolves into [I will ascend to the VIP Lounge and slaughter every single God who donated to watch me bleed].
3. **The Audience Dynamic**: The higher beings view humans as fighting crickets. The MC views the higher beings as gullible, easily manipulated "ATM Machines" who are easily swayed by internet drama.', @method_id, 1, 2, NOW()),

-- 3. System Mechanics
('death-system-mechanics-setting-gen', '生成「System Mechanics」：设计视网膜弹幕、打赏商城与金主“星痕”机制', 'Generate System Mechanics for Death Game',
'## 「System Mechanics」生成 — 死亡直播赛

在没有法律的死亡赛区里，【打赏值/星币】是唯一能救命的真理。

### 生成指南
1. **The Streaming Interface (视网膜弹幕)**：弹幕是有颜色等级的。白嫖怪只能发白字；VVIP大能（比如：深渊魔王、奥林匹斯宙斯）发的是闪瞎眼的金色全屏弹幕，甚至会引起空间震荡。
2. **The Sponsor System (星痕/打赏机制)**：主角打出高光时刻会获得打赏。如果被某个顶级大佬看中（成为专属金主/赞助商），就能借用该大佬的绝招（Stigma/星痕）。比如打赏了10万硬币，临时借主角用一次“雷神之锤”。
3. **The Penalty/Bounty (掉粉危机)**：如果主角试图逃避战斗（挂机），平台判定“观赏性太低”，会立刻给主角叠加剧毒Debuff，或者全地图通报他的位置，引来追杀。逼着主角一直处在高压战斗中。',
'## "System Mechanics" Generation — Death Game

In a lawless death arena, [Donated Coins] are the only truth that can save your life.

### Guide
1. **The Streaming Interface**: Chat messages have color tiers. Free-loaders send white text. VVIP Gods (e.g., The Abyssal Lord, Zeus) send blinding, golden screen-shaking messages that physically vibrate the air. 
2. **The Sponsor System**: Hype moments earn donations. If a top-tier God selects the MC as their "Incarnation/Sponsored Streamer," the MC can borrow their signature Stigma. (e.g., God tips 100,000 Coins -> MC gets to use "Thor''s Hammer" for exactly 10 seconds).
3. **The Penalty/Bounty (Unsubscribing)**: If the MC tries to hide/camp (low entertainment value), the Platform Artificial Intelligence immediately applies a fatal poison Debuff or broadcasts their exact coordinates to all monsters. This forces the MC into constant, high-stress, bloody action.', @method_id, 1, 3, NOW()),

-- 4. Worldbuilding
('death-worldbuilding-setting-gen', '生成「Worldbuilding」：设计看热闹的傲慢星神、残酷剧本和直播系统的高层架构', 'Generate Worldbuilding for Death Game',
'## 「Worldbuilding」生成 — 死亡直播赛

世界观是被**严重物化和娱乐化**的末日。

### 生成指南
1. **The Constellations (星神/观众群)**：他们可能是各个神话的诸神（北欧、希腊、克苏鲁），或者是高度进化的外星大帝。因为活得太久极其无聊，他们需要看低级文明挣扎来取乐。
2. **The Game Structure (剧本/主线)**：地球被划分为一个个“剧本区（Scenarios）”。有的是“在丧尸潮中守护旗帜一小时”，有的是“让两个队伍互相残杀直到剩下一人”。
3. **The True Organizers (管理层)**：平台背后的真正掌控者。绝对中立、冷血、按收视率分配资源的“主系统（The Star Stream / Dokkaebi）”。',
'## "Worldbuilding" Generation — Death Game

The apocalypse has been **severely objectified and commodified into pure entertainment.**

### Guide
1. **The Constellations (The Viewers)**: They might be mythic gods (Norse, Greek, Eldritch) or highly evolved alien emperors. Having lived too long and grown chronically bored, they consume the struggles of lower-tier civilizations as reality TV.
2. **The Game Structure (Scenarios)**: Earth is carved into "Scenarios." Scenario 1: "Survive a Zombie horde for 1 hour." Scenario 2: "Kill everyone on the opposing team until only one survives." 
3. **The True Organizers (The Bureaucracy)**: The absolute rulers behind the broadcasting platform. A coldly neutral, viewership-driven Artificial Intelligence or High Council (like the System / Dokkaebis in ORV).', @method_id, 1, 4, NOW()),

-- 5. Writing Style
('death-writing-style-setting-gen', '生成「Writing Style」：指导血腥肉搏与弹幕疯狂刷屏的无缝切换', 'Generate Writing Style for Death Game',
'## 「Writing Style」生成 — 死亡直播赛

写作的精髓在于**极致的双线反差**：主角这边骨断筋折鲜血淋漓，而弹幕那边却在喝啤酒吃爆米花。

### 生成指南
1. **Intercutting Chat (弹幕穿插法)**：
   - *（主角刚刚用断掉的肋骨刺穿了队友的心脏，因为规则只能活一个。他浑身是血地跪在地上喘息。）*
   - 紧接着插入一句：`[星神“猎血的狂欢者”为了这绝妙的反叛赞助了 10,000 枚星币！] / ["绝望的救赎者"表示这剧情太狗血了，退订！]`
2. **Pacing of Stakes (收视率压迫)**：危机绝不能仅仅是“怪物强”。最致命的危机往往是系统提示**【您的当前收视率已跌破底线，5分钟后将进行抹杀】**。这逼迫主角必须做出更加疯狂、出人意料的举动（也就是整活）。
3. **第四面墙（The Camera）**：主角要在最高潮的时刻，抬头对着虚空中的“隐形无人机（观众）”竖起中指，或者露出一个邪恶的微笑。这种挑衅能彻底点燃打赏狂潮。',
'## "Writing Style" Generation — Death Game

The essence of the writing is the **extreme dual-line contrast**: The MC is bleeding out with shattered bones, while the chat is eating popcorn.

### Guide
1. **Intercutting Chat**:
   - *(The MC has just used their own broken rib to stab a teammate because the rules stated only one can live. The MC is kneeling in a pool of blood, gasping for air.)*
   - Immediately insert: `[Constellation "Blood-Crazed Reveler" is thrilled by this brilliant betrayal and sponsors 10,000 Coins!] / [Constellation "Despairing Redeemer" thinks this is too edgy and unsubscribes.]`
2. **Pacing of Stakes (Viewership Pressure)**: The threat shouldn''t just be a "strong monster." The deadliest threat is the system prompt: **[Your Viewership has dropped below the minimum threshold. Eradication in 5 minutes.]** This forces the MC to pull off insanely dangerous, unexpected stunts ("do it for the vine") just to survive.
3. **Breaking the Fourth Wall (The Camera)**: At the climax of a fight, the MC must look directly up at the invisible cosmic drones and flip them the bird, or flash a psychotic, blood-soaked smile. This arrogance completely ignites the tipping frenzy.', @method_id, 1, 5, NOW()),

-- 6. Character
('death-character-gen', '「角色」生成：生成唯利是图的直播主角、恶趣味的神明金主与炮灰队友', 'Generate money-grubbing MC, sadistic god sponsors, and cannon fodder teammates',
'## 「角色」生成 — 死亡直播赛

角色分为“被困在玻璃罐里的虫子（玩家）”和“玻璃罐外撒饲料的小孩（神明）”。

### 角色设计重点
1. **The Protagonist (主播/化身)**：
   - 极其擅长情绪控制。内心可能因为同伴的死悲痛欲绝，但为了利用那些喜欢“冷血戏码”的神明赚取硬币给同伴买复活药，表面上必须装出极其残忍、享受杀戮的变态模样。
2. **Sugar-Daddy Constellation (榜一大哥/专属赞助商)**：
   - 大多是心理变态或乐子人。比如【深渊的凝视者】。他狂砸几百万星币给主角，不是因为善良，而是想看主角在绝望中如何像狗一样挣扎着活下去。
3. **Sadistic Game Master (狗策划/鬼怪经纪人)**：
   - 漂浮在半空、专门负责调动气氛和颁布残忍任务的主持人。永远带着职业化的假笑：“哎呀哎呀，各位星神大人觉得太无聊了嘛？那我们现在把重力增加十倍如何？”',
'## "Character" Generation — Death Game

Characters are divided into "The bugs trapped in the glass jar (Players)" and "The children outside tapping the glass and dropping breadcrumbs (Gods)."

### Design Focus
1. **The Protagonist (The Streamer/Incarnation)**:
   - A master of emotional manipulation. Internally, they might be weeping over a teammate''s death. But to earn enough Coins from the sadistic Gods to buy a Resurrection Potion, they force a psychopathic, bloodthirsty grin to the camera.
2. **Sugar-Daddy Constellation (VIP Sponsor)**:
   - Mostly sadists or bored trolls. e.g., [The Abyss Stander]. They drop millions of Coins on the MC not out of kindness, but because they have a fetish for watching humans struggle like feral dogs in utter despair.
3. **Sadistic Game Master (Dokkaebi / Platform Manager)**:
   - Floating, fluffy, or cybernetic Hosts responsible for hyping the crowd and issuing cruel missions. Always wearing a professional, sociopathic smile: *"Oh my, are the Constellations feeling bored? Shall we increase the gravity by 10x and drop a Dragon in? Let''s see them dance!"*', @method_id, 1, 21, NOW()),

-- 7. Faction
('death-faction-gen', '「势力」生成：生成垄断排行榜的地球公会、派系对立的天神娱乐公司', 'Generate ranked Earth Guilds and clashing Cosmic Pantheons',
'## 「Faction (势力/组织)」生成 — 死亡直播赛

势力的角逐是在“下界”和“上界”同时进行的。

### 势力设计指南
1. **Player Alliance / Guild (地球的高玩公会)**
   - 例：霸王俱乐部、先知同盟。
   - **特点**：他们像现代的跨国财阀一样垄断了“高质量的打赏”。他们会霸占资源区，并在镜头前上演极其做作的“英雄救美”戏码来骗取诸神的打赏。
2. **Constellation Pantheon (星神大系/娱乐公司)**
   - 例：奥林匹斯集团（主打英雄主义与肉体对抗直播区）、克苏鲁深渊网（主打精神污染与恐怖猎奇直播区）。
   - **斗争方式**：天神之间不能直接动手，所以他们砸钱给地球上的“化身/代理人”。如果奥林匹斯的代理人把克苏鲁的代理人杀了，克苏鲁那一派的收视率就会大跌。',
'## "Faction" Generation — Death Game

Factional warfare occurs simultaneously in the "Lower Realm" and the "Upper Realm."

### Design Guide
1. **Player Alliance / Guild (Top Earth Streams)**
   - e.g., Overlord Club, Prophets'' Syndicate.
   - **Characteristics**: Operating like modern multinational corporations, they monopolize "high-engagement zones." They will aggressively secure resources and perform incredibly staged, highly dramatized "Hero saves the damsel" plays purely to bait donations from gullible Gods.
2. **Constellation Pantheon (Cosmic Entertainment Networks)**
   - e.g., Mt. Olympus Group (Focuses on Heroic/Gladiator physical combat streams), The Abyssal Deep Web (Focuses on Psychological Torture and Eldritch horror streams).
   - **Combat Method**: Gods cannot directly intervene. Thus, they throw massive funding at their human "Incarnations" as proxies. If Olympus''s proxy beheads the Abyss''s proxy, the Abyss faction loses stock value and viewership.', @method_id, 1, 41, NOW()),

-- 8. Scene
('death-scene-gen', '「场景」生成：生成遍布陷阱的末日竞技场与极尽奢华的宇宙VIP休息室', 'Generate lethal death arenas and the opulent VIP viewing lounges',
'## 「Scene (场景)」生成 — 死亡直播赛

场景就是杀人机器。

### 场景设计指南
1. **Death Game Arena (血腥死亡游戏场)**
   - 就是我们原本熟悉的街道、学校、地铁，但被加了致命的规则。
   - *案例*：整个时代广场变成了一个巨大的跳房子棋盘。如果在五秒内没有跳到亮红灯的盒子里，就会被天基激光直接汽化。
2. **The Waiting Room / Shop (安全屋/商城休息区)**
   - *氛围*：短暂的宁静。白色的无菌空间，中心有一台漂浮的全息贩卖机。玩家在这里清点带血的硬币，购买绷带和属性点。气氛极其压抑，因为几分钟后门打开，又是下一场杀戮。
3. **The Cosmic VIP Lounge (天神的看台)**
   - *反差感*：用文字侧写天神的视角。他们坐在比银河系还大的沙发上，喝着超星星爆炸提炼的红酒，看着面前几十亿个屏幕里正在惨叫的人类，像是在看赛马。',
'## "Scene" Generation — Death Game

The Scene itself is a murder weapon designed for peak entertainment.

### Design Guide
1. **Death Game Arena (The Bloodstage)**
   - Familiar urban locations (schools, subways, Times Square) artificially warped by lethal rules.
   - *Example*: Times Square transformed into a gigantic, deadly Hopscotch board. Failing to jump onto the red-lit square within 5 seconds results in instant vaporization by an orbital laser.
2. **The Waiting Room / Shop (The Safe Zone)**
   - *Atmosphere*: Brief, heavy silence. A sterile white cubic room with a floating holographic vending machine in the center. Players nervously count their blood-soaked Coins here, buying bandages and Stat points. The oppression is suffocating, knowing the door opens to the next meat grinder in exactly 60 seconds.
3. **The Cosmic VIP Lounge (The Gods'' View)**
   - *Contrast*: Extrapolate the viewers'' perspective. Sitting on couches larger than galaxies, sipping wine distilled from Supernovas, watching billions of holographic screens displaying screaming humans as if they were watching horse racing.', @method_id, 1, 61, NOW()),

-- 9. Plot
('death-plot-gen', '「情节Plot」：指导如何设计骗取打赏、越级反杀与掀翻直播平台的剧情弧线', 'Guide to design farming donations, cross-tier kills, and overthrowing the system',
'## 剧情设计指南 (Plot Design) — 死亡直播赛

核心的主线是**“赚流量 - 升级 - 成为顶流 - 最终把资本家（平台）挂在路灯上”**。

### 核心情节弧线
1. **默默无闻的开局 (The No-Name Streamer)**：主角没有初始资金，被分配在最烂的死亡关卡。凭着异于常人的果断（比如毫不犹豫砍断自己被咬的左臂），成功引起了某位小众/变态星神的注意，获得了第一笔打赏（The First Tip）。
2. **整活与流量爆炸 (Going Viral)**：主角发现按部就班过关赚得太少。于是开始“卡Bug”或者“做出极其极端的反转（比如把不可一世的高玩踩在脚下疯狂扇耳光）”。系统疯狂提示：【您的观赏度极强，收视率飙升至全频第一！】。
3. **金主与神罚 (The Sponsor''s Wrath)**：主角拒绝了某个霸道天神的“专属契约”。天神大怒，立刻发布了全服高价悬赏要主角的命。主角被迫上演一场绝地求生的大逃杀，反而因此打破了历史最高收视记录。
4. **掀翻棋盘 (Destroying the Server)**：最终期，当主角集齐了所有的积分。他不买武器，而是把所有的积分全部用来购买【最高级平台管理员临时权限】。关闭了惩罚系统，直接冲烂了天神的观景区。',
'## Plot Design Guide — Death Game / Cosmic Streamer

The core plotline is essentially: **"Farm Clout -> Level Up -> Become the Top Streamer -> Eventually hang the Platform Capitalists from the streetlights."**

### Core Story Arcs
1. **The No-Name Streamer**: Began with zero capital, assigned to the worst death scenario. Through sheer, terrifying decisiveness (like chopping off his own bitten arm without bleeding a tear), he catches the eye of a niche, sadistic Constellation. He earns "The First Tip."
2. **Going Viral (The Hype Moments)**: The MC realizes playing by the rules earns pennies. He begins "Exploiting Bugs" or executing extreme mental twists (e.g., kidnapping the arrogant #1 ranked player and humiliating them live). System spams: **[Entertainment value is astronomical! Your channel has skyrocketed to #1 Trending!]**
3. **The Sponsor''s Wrath**: The MC rejects a tyrannical God''s demand for an "Exclusive Sponsorship Contract." Furious, the God issues a server-wide bounty on the MC''s head. The MC is hunted by top players in a massive Battle Royale—but the sheer epic scale of his survival ends up shattering the all-time viewership records.
4. **Destroying the Server**: The Climax. Having amassed a trillion Coins, the MC doesn''t buy a divine sword. Instead, he spends every single coin to purchase [Temporary Platinum Administrator Privileges]. He forcefully shuts down the death-game barriers and breaks straight through into the Gods'' safe VIP viewing lounges with a chainsaw.', @method_id, 1, 100, NOW()),

-- 10. Narrative
('death-narrative', '「叙事与描写 Narrative」：指导冷静的战斗描写与疯狂的系统弹幕形成的心理冲击', 'Guide to blending cold combat descriptions with explosive chat box adrenaline',
'## 叙事与描写技巧 (Narrative) — 死亡直播赛

文本的信息密度要高，必须随时有一种**“电竞直播查房”**的热烈感与死亡游戏**“绞肉机”**残留的血腥味。

### 1. 弹幕作为情绪放大器 (Chat as Hype Amplifiers)
- 动作描写高潮处，必须插入弹幕。
- *描写示范*：怪物庞大的身躯轰然倒塌，内脏流了一地。主角抹去护目镜上的血浆，连粗气都没喘。 
  `[星神“寂静的裁决者”对您的干脆利落感到一阵战栗！]`
  `[“深海暴君”打赏了 50,000 星币！并且向您发送了一个“太棒了”的血腥表情包！]`

### 2. 死亡的随时降临 (The Fragility of Life)
- 不要用冗长的篇幅写配角的死亡。死亡在这本书里是【突然且廉价的】。
- *描写示范*：上一秒还在滔滔不绝分析战术的职业玩家，随着半空中隐形的激光扫过，他的上半身平滑地滑落到了地上。弹幕立刻刷过一片对他的嘲笑声。主角连看都没看这具尸体一眼。

### 3. 系统音的催命感 (The System''s Ticking Clock)
- 将系统提示语粗体化，当成倒计时。
- **【警告：由于长达3分钟没有发生流血事件，当前区域将启动毒气注入。】**',
'## Narrative and Writing Techniques — Death Game

The information density must be high, constantly maintaining the intense, dopamine-fueled high of a **"Twitch Stream hype moment"** mixed with the nauseating stench of an **"apocalyptic meat grinder."**

### 1. Chat as Hype Amplifiers
- At the climax of an action sequence, you MUST inject the chat.
- *Example*: The Abomination''s massive corpse crashed to the ground, its entrails painting the concrete. The MC wiped the thick gore from his visor, not even panting.
  `[Constellation "Silent Adjudicator" shudders at your ruthless efficiency!]`
  `[Constellation "Deep Sea Tyrant" has tipped 50,000 Coins! And sent a bloody "Fantastic!" animated emote!]`

### 2. The Absolute Fragility of Life
- Do not write drawn-out, emotional monologues for the deaths of side characters. Death here is [Sudden and Cheap].
- *Example*: The pro-gamer was mid-sentence proudly explaining his flawless strategy—when an invisible orbital laser swept past. The top half of his body slid smoothly off his torso onto the floor. The chat instantly flooded with blue holograms laughing at his stupidity. The MC didn''t even glance at the corpse.

### 3. The System as the Grim Reaper
- Bold the system prompts; use them as a merciless ticking clock.
- **[WARNING: Due to a lack of bloodshed for 3 minutes, Neurotoxin injection has commenced in your zone. Entertain us or die.]**', @method_id, 1, 101, NOW()),

-- 11. Novel Naming
('death-novel-naming', '「书名与大纲生成」：指导生极具竞技场网感与平台大老板质感的作品名称', 'Guide to generating competitive-arena and streaming-platform flavored titles',
'## 书名与大纲生成指南 — 死亡直播赛

书名必须具有强烈的**网络时代特质**和**狂放的野心**。读起来要有《全知读者视角》或韩国生存系网漫的紧凑感。

### 1. Title Generation (书名命名偏好)
- **网感/弹幕风**：`[Stream / Gods] + [Are Doing Something Extreme To Me]` (例：*The Constellations Are Crazy About Me*, *Surviving the Cosmic Stream*, *God''s Favorite Pay-to-Win Streamer*)
- **大逃杀杀手风**：`[Player/Returner/Ranker] + [Is Overpowered/Breaking the Game]` (例：*The Tutorial is Too Hard*, *Omniscient Reader’s Viewpoint*, *Solo Bug-Abuser in the Death Game*)

### 2. Synopsis Generation (三段式大纲结构)
- **第一段：常理的崩塌 (The End of Normalcy)**：直接写出日常是如何在一瞬间变成了血腥电视节目的。如地球上方出现了巨大的计分板，神明开始投注。主角原本是个最平庸的社畜。
- **第二段：掌握密码 (Cracking the Algorithm)**：主角发现传统的“努力杀怪”根本赚不到钱。他洞悉了直播系统的本质是“流量”。他开始兵行险着，专门做那些让神明大呼过瘾的变态反转操作。成为了全宇宙最臭名昭著但也最吸金的黑马。
- **第三段：向资本开战 (Declaring War on the Server)**：积攒了常人无法想象的“打赏星币”后，他不打算继续当猴子了。简介收尾要极其霸气。发出誓言：要把那些高居云端看戏的神明，一个个拉下来变成他的直播垫脚石。',
'## Title & Synopsis Generation Guide — Death Game / Cosmic Streamer

Titles must possess a strong **Internet/Gaming Era flavor** combined with **unbridled arrogance**. Must read with the tight, punchy energy of Korean webtoons (like ORV).

### 1. Title Generation Preferences
- **Stream/Chat Flavor**: `[Stream / Constellations / Gods] + [Action/Extreme Descriptor]` (e.g., *The Constellations Are Crazy About Me*, *Surviving the Cosmic Broadcast*, *God''s Favorite P2W Streamer*).
- **Ranker/Death Game Flavor**: `[Ranker / Player / Returner] + [Breaking the rules / Overpowered trait]` (e.g., *The Tutorial is Too Hard*, *Omniscient Streamer*, *Solo Bug-Abuser in the Death Game*).

### 2. Synopsis Generation (Three-Act Structure)
- **Act 1: The End of Normalcy**: State directly how normal life collapsed into a bloody TV show in a split second. A giant scoreboard appears over the Earth; alien Gods place their bets. The MC was just an average office worker.
- **Act 2: Cracking the Algorithm**: The MC realizes that "fighting hard honorably" earns zero tips. He cracks the code: this is about TRAFFIC. He starts pulling off suicidal, insanely controversial, and psychologically manipulative stunts specifically to make the Gods scream in hype. He becomes the most infamous, but highest-paid dark horse in the universe.
- **Act 3: Declaring War on the Server**: Having accumulated a literal galaxy''s worth of Subscriptions and Tips, he is done being the dancing monkey. Close with extreme arrogance: He swears to use the System''s own money to drag the Gods down from their VIP chairs and turn them into his content-fodder.', @method_id, 1, 102, NOW()),

-- 12. Entity Naming
('death-entity-naming', '「名词生成指南」：指导生成中二度拉满的星神尊名与残酷的游戏关卡名称', 'Guide to generating edgy Constellation monikers and brutal Death Game scenarios',
'## 专有名词生成指南 (Entity Naming) — 死亡直播赛

由于是“网名”，所以星神的尊名必须具有**高度的概括性、隐喻和中二感**，像极了土豪玩家砸钱时亮出的ID特效。

### 1. 星神/榜一大哥的尊名 (Constellation Monikers)
- 格式：`[Adjective/Verb] + [Noun related to their domain]`，由于是翻译腔，一定要显得格局极大。
- *案例（暗黑风）*：The Demon-like Judge of Fire (如同恶魔般的火之审判者), Prisoner of the Golden Headband (紧箍儿的囚徒 - 暗示孙悟空), Architect of the Abyss (深渊的建筑师)。
- *案例（搞笑网感风）*：The God of Keyboard Sniping (键盘狙击之神), Bored Overlord (无聊的霸王)。

### 2. 直播系统术语 (System & Platform Terms)
- 将无情的资本运作包装成高大上的天网系统。
- *案例*：The Star Stream (星流网), The Akashic Records Broadcast (阿卡夏记录频道), The Dokkaebi Bureau (鬼怪管理局局).

### 3. 死亡剧本/关卡 (Scenarios & Items)
- 名字越平淡无奇，规则越血腥绝望。
- *案例*：Scenario #4: The King''s Qualification (第四剧本：王者的资格 - 实际上要求杀掉一半的臣民); Scenario #12: Hide and Seek (捉迷藏 - 被抓到直接灵魂溶解)。

**AI 动作要求**：在生成星神（Constellation）的名字时，必须使用**【长定语修饰的名词】**（如：掌握XX的XXX），并且名字本身要能暗示祂的真实神话身份。在生成道具或关卡时，强烈强调【娱乐至死】和【资本剥削】的网游道具质感。',
'## Entity Naming Guide — Death Game

Since these are essentially "Usernames," Constellation Monikers must be **highly descriptive, metaphorical, and incredibly edgy (Chuunibyou)**, capturing the exact vibe of an internet whale flexing their VVIP title badges in chat.

### 1. Constellation Monikers (The Sugar-Daddy Gods)
- Format: `[Descriptive Adjective or Action] + [Noun related to their domain]`. Must sound incredibly grandiose.
- *Examples (Epic/Dark)*: The Demon-like Judge of Fire (hints at Archangel Uriel), The Prisoner of the Golden Headband (hints at Sun Wukong), Architect of the Abyss.
- *Examples (Internet Troll)*: The God of Keyboard Sniping, The Bored Overlord.

### 2. Platform Terminology
- Dress up ruthless capitalistic exploitation with cosmic, grandiose terms.
- *Examples*: The Star Stream, The Akashic Broadcasting Network, The Dokkaebi Management Bureau.

### 3. Scenarios & Death Games
- The simpler the name, the bloodier and more twisted the actual rules are.
- *Examples*: Scenario #4: The King''s Qualification (actually requires you to slaughter half your own subjects). Scenario #12: Hide and Seek (being ''Found'' means getting your soul dissolved by acid).

**AI Action Requirement**: When generating Constellation names, you MUST use the **[Long Descriptive Noun Phrase]** format (e.g., The [Adjective] [Noun] of [Domain]), which subtly hints at their true historical or mythological identity. When generating game modes or items, heavily highlight the "Entertainment to Death" and "P2W Capitalist Exploitation" MMORPG vibe.', @method_id, 1, 103, NOW())
ON DUPLICATE KEY UPDATE description=VALUES(description), instructions=VALUES(instructions);
